controllers:
    resource: ../src/Controller/
    type: attribute
app_lucky_number:
    path: /lucky/number
    controller: App\Controller\LuckyController::number
app_hello:
    path: /hello
    controller: App\Controller\HelloController